// react/src/routes/Home.jsx
import { useState, useEffect } from "react";
import Hero from "../components/Hero";
import Article from "../components/Article";
import { directus } from "../services/directus";
import { formatRelativeTime } from "../../../shared/utils/format-relative-time";

export default function Home() {
  const [hero, setHero] = useState(null);
  const [articles, setArticles] = useState(null);

  useEffect(() => {
    async function fetchData() {
      const response = await directus.items("articles").readMany({
        fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
        sort: "-publish_date",
      });

      const formattedArticles = response.data.map((article) => {
        return {
          ...article,
          publish_date: formatRelativeTime(new Date(article.publish_date)),
        };
      });

      const [first, ...rest] = formattedArticles;
      setHero(first);
      setArticles(rest);
    }
    fetchData();
  }, []);

  return (
    <main>
      <section className="main-content">
        <div className="container">
          {hero && <Hero article={hero} />}
          {articles && (
            <div className="articles-grid">
              {articles.map((article, index) => (
                <Article
                  key={index}
                  article={article}
                  bordered={index !== articles.length - 1}
                />
              ))}
            </div>
          )}
        </div>
      </section>
    </main>
  );
}

// angular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { directus } from 'src/app/services/directus';
import { formatRelativeTime } from '../../../../../shared/utils/format-relative-time.js';

@Component({
  selector: 'page-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomePage implements OnInit {
  hero: Record<string, any> | null = null;
  articles: Record<string, any>[] | null = null;

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.fetchData();
  }

  async fetchData() {
    const response = await directus.items('articles').readMany({
      fields: ['*', 'author.avatar', 'author.first_name', 'author.last_name'],
      sort: ['-publish_date'],
    });

    if (!response.data) {
      this.router.navigate(['404']);
      return;
    }

    const formattedArticles = response.data.map((article) => {
      return {
        ...article,
        publish_date: formatRelativeTime(new Date(article.publish_date)),
      };
    });

    const [first, ...rest] = formattedArticles;
    this.hero = first;
    this.articles = rest;
  }
}

<main>
  <section class="main-content">
    <div class="container">
      <app-hero [article]="hero"></app-hero>
      <div class="articles-grid">
        <ng-container *ngIf="articles">
          <app-article
            *ngFor="let article of articles; let articleIndex = index"
            [article]="article"
            [bordered]="articleIndex !== articles.length - 1"
          ></app-article>
        </ng-container>
      </div>
    </div>
  </section>
</main>
