// remix/app/components/MoreArticles.jsx
import Article from "~/components/Article";
import { getDirectusClient } from "~/lib/directus";

export default function MoreArticles({ articles }) {
  return (
    <section className="more-articles">
      <div className="container">
        <h1 className="more-articles__title">More Articles</h1>
        {articles?.length !== 0 && (
          <div className="articles-grid">
            {articles?.map((article, index) => (
              <Article
                key={index}
                article={article}
                bordered={index !== articles.length - 1}
              />
            ))}
          </div>
        )}
      </div>
    </section>
  );
}

// sveltekit/src/lib/components/MoreArticles.svelte
<script>
	import Article from '$lib/components/Article.svelte';
	export let articles;
</script>

<section class="more-articles">
	<div class="container">
		<h1 class="more-articles__title">More Articles</h1>
		<div class="articles-grid">
			{#each articles as article, index}
				<Article {article} bordered={index !== articles.length - 1} />
			{/each}
		</div>
	</div>
</section>
