// react/src/components/Header.jsx
import IconMonospace from "./icons/Monospace";

export default function Header() {
  return (
    <header>
      <nav className="container">
        <a href="/">
          <IconMonospace />
        </a>
        <span className="header__description">
          An example site powered by <span className="accent">React</span> and{" "}
          <span className="accent">Directus</span>.
        </span>
      </nav>
    </header>
  );
}

// vue/src/components/Header.vue
<script setup>
import IconMonospace from "./icons/Monospace.vue";
</script>

<template>
  <header>
    <nav class="container">
      <a href="/">
        <IconMonospace />
      </a>
      <span class="header__description">
        An example site powered by <span class="accent">Vue</span> and
        <span class="accent">Directus</span>.
      </span>
    </nav>
  </header>
</template>
