// blitz/app/components/Notice.jsx
export default function Notice() {
  return (
    <div className="notice">
      <div className="container">
        <span>
          The source code for this blog is{" "}
          <a href="https://github.com/directus/examples">available on GitHub.</a>
        </span>
        <i className="material-icons-outlined">close</i>
      </div>
    </div>
  )
}

// vue/src/components/Notice.vue
<template>
  <div class="notice">
    <div class="container">
      <span
        >The source code for this blog is
        <a href="https://github.com/directus/examples"
          >available on GitHub.</a
        ></span
      >
      <i class="material-icons-outlined">close</i>
    </div>
  </div>
</template>
