// website-next13/app/[slug]/page.tsx
import directus from "lib/directus"
import { notFound } from "next/navigation"

async function getPage(slug) {
  try {
    const page = await directus.items('pages').readOne(slug)
    return page
  } catch(error) {
    notFound()
  }
}

export default async function DynamicPage({ params }) {
  const page = await getPage(params.slug)
  return (
    <div>
      <h1>{page.title}</h1>
      <div dangerouslySetInnerHTML={{ __html: page.content }}></div>
    </div>
  )
}

// website-nuxt3/pages/[slug].vue
<template>
  <h1>{{page.title}}</h1>
  <div v-html="page.content"></div>
</template>

<script setup>
  const { $directus } = useNuxtApp()
  const route = useRoute()
  const { data: page } = await useAsyncData('page', () => {
    return $directus.items('pages').readOne(route.params.slug)
  })
  if (!page.value) throw createError({ 
    statusCode: 404, 
    statusMessage: 'Page Not Found' 
  })
</script>
