// sveltekit/src/routes/index.svelte
<script context="module">
	/** @type {import('@sveltejs/kit').Load} */
	export async function load({ fetch }) {
		const url = `/index.json`;
		const response = await fetch(url);

		if (!response.ok) {
			return {
				status: 404
			};
		}

		const data = await response.json();

		return {
			props: {
				hero: data.hero,
				articles: data.articles
			}
		};
	}
</script>

<script>
	import Hero from '$lib/components/Hero.svelte';
	import Article from '$lib/components/Article.svelte';

	export let hero, articles;
</script>

<main>
	<section class="main-content">
		<div class="container">
			<Hero article={hero} />
			<div class="articles-grid">
				{#each articles as article, index}
					<Article {article} bordered={index !== articles.length - 1} />
				{/each}
			</div>
		</div>
	</section>
</main>

// remix/app/routes/index.jsx
import { json, useLoaderData } from "remix";
import Hero from "~/components/Hero";
import Article from "~/components/Article";
import { getDirectusClient } from "~/lib/directus";
import { formatRelativeTime } from "../../../shared/utils/format-relative-time";

export const loader = async () => {
  const directus = await getDirectusClient();

  const response = await directus.items("articles").readMany({
    fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
    sort: "-publish_date",
  });
  const formattedArticles = response.data.map((article) => {
    return {
      ...article,
      publish_date: formatRelativeTime(new Date(article.publish_date)),
    };
  });

  if (!formattedArticles) {
    throw new Response("Articles not found", {
      status: 404,
    });
  }

  const [hero, ...articles] = formattedArticles;

  return json({ hero, articles });
};

export default function Index() {
  const data = useLoaderData();

  return (
    <main>
      <section className="main-content">
        <div className="container">
          <Hero article={data.hero} />
          <div className="articles-grid">
            {data.articles.map((article, index) => (
              <Article
                key={index}
                article={article}
                bordered={index !== data.articles.length - 1}
              />
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
