// qwik/src/routes/index.tsx
import { component$, useSignal, useTask$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";

import Hero from "../components/Hero";
import Article from "~/components/Article";

import { directus } from "../services/directus";
import { formatRelativeTime } from "../utils/format-relative-time";

export const head: DocumentHead = {
  title: "Welcome to Qwik & Directus",
  meta: [
    {
      name: "description",
      content: "A Qwik & Directus example app",
    },
  ],
};


export default component$(() => {
  const hero = useSignal(null);
  const articles = useSignal([]);

  useTask$(async () => {
    async function fetchData() {
      const response = await directus.items("articles").readByQuery({
        fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
        sort: "-publish_date",
      });

      const formattedArticles = response.data.map((article) => {
        return {
          ...article,
          publish_date: formatRelativeTime(new Date(article.publish_date)),
        };
      });

      const [first, ...rest] = formattedArticles;
      hero.value = first;
      articles.value = rest;
    }
    await fetchData();
  });

  return (
    <main>
      <section class="main-content">
        <div class="container">
          {hero.value && <Hero article={hero} />}

          {articles.value && (
            <div class="articles-grid">
              {articles.value.map((article, index) => (
                <Article
                  key={index}
                  article={article}
                  bordered={index !== articles.length - 1}
                />
              ))}
            </div>
          )}
        </div>
      </section>
    </main>
  );
});

// remix/app/routes/index.jsx
import { useLoaderData } from "@remix-run/react";
import { json } from "@remix-run/node";
import Hero from "~/components/Hero";
import Article from "~/components/Article";
import { getDirectusClient } from "~/lib/directus";
import { formatRelativeTime } from "~/utils/format-relative-time";

export const loader = async () => {
  const directus = await getDirectusClient();

  const response = await directus.items("articles").readByQuery({
    fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
    sort: "-publish_date",
  });
  const formattedArticles = response.data.map((article) => {
    return {
      ...article,
      publish_date: formatRelativeTime(new Date(article.publish_date)),
    };
  });

  if (!formattedArticles) {
    throw new Response("Articles not found", {
      status: 404,
    });
  }

  const [hero, ...articles] = formattedArticles;

  return json({ hero, articles });
};

export default function Index() {
  const data = useLoaderData();

  return (
    <main>
      <section className="main-content">
        <div className="container">
          <Hero article={data.hero} />
          <div className="articles-grid">
            {data.articles.map((article, index) => (
              <Article
                key={index}
                article={article}
                bordered={index !== data.articles.length - 1}
              />
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
