// nextjs/pages/articles/[id].jsx
import Link from "next/link";
import { getDirectusClient } from "../../lib/directus";
import MoreArticles from "../../components/MoreArticles";
import IconBack from "../../components/icons/Back";
import IconLink from "../../components/icons/Link";
import IconGithub from "../../components/icons/Github";
import IconYoutube from "../../components/icons/Youtube";
import IconLinkedin from "../../components/icons/Linkedin";
import IconTwitter from "../../components/icons/Twitter";
import { formatRelativeTime } from "../../utils/format-relative-time";
import { getAssetURL } from "../../utils/get-asset-url";

export default function ArticlePage({ article, moreArticles }) {
  return (
    <div className="current-article">
      <section>
        <div className="container">
          <Link href="/" className="current-article__backlink">

            <IconBack className="icon" />
            <span>Back to Articles</span>

          </Link>
          <h1 className="current-article__title">{article.title}</h1>
          <div className="current-article__detail">
            <div className="current-article__wrapperOuter">
              <div className="current-article__wrapperInner">
                <div className="current-article__authorImage">
                  <img
                    src={getAssetURL(article.author.avatar)}
                    alt=""
                    loading="lazy"
                  />
                </div>
                <div>
                  <div className="current-article__authorName">
                    {`${article.author.first_name} ${article.author.last_name}`}
                  </div>
                  <div className="current-article__time">
                    {article.publish_date}
                  </div>
                </div>
              </div>
              <ul className="current-article__socials">
                <li>
                  <a
                    href={`/articles/${article.id}`}
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconLink />
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.youtube.com/c/DirectusVideos"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconYoutube />
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.linkedin.com/company/directus-io"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconLinkedin />
                  </a>
                </li>
                <li>
                  <a
                    href="https://twitter.com/directus"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconTwitter />
                  </a>
                </li>
              </ul>
            </div>
            <div className="current-article_coverImage">
              <img src={getAssetURL(article.cover_image)} alt="" />
            </div>
          </div>
          <div className="current-article__body">
            <div
              className="current-article__bodyContent"
              dangerouslySetInnerHTML={{ __html: article.body }}
            ></div>
            <ul className="current-article__bodySocials">
              <li>
                <a
                  href="https://github.com/directus"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  <IconGithub />
                </a>
              </li>
              <li>
                <a
                  href="https://www.youtube.com/c/DirectusVideos"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  <IconYoutube />
                </a>
              </li>
              <li>
                <a
                  href="https://www.linkedin.com/company/directus-io"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  <IconLinkedin />
                </a>
              </li>
              <li>
                <a
                  href="https://twitter.com/directus"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  <IconTwitter />
                </a>
              </li>
            </ul>
          </div>
        </div>
      </section>
      <MoreArticles articles={moreArticles} />
    </div>
  );
}

export async function getStaticPaths() {
  const directus = await getDirectusClient();
  const { data } = await directus.items("articles").readByQuery({
    fields: "id",
    filter: { status: { _eq: "published" } },
    limit: -1,
  });
  return {
    paths: data.map((article) => {
      return {
        params: { id: article.id.toString() },
      };
    }),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const { id } = params;

  const directus = await getDirectusClient();

  const article = await directus.items("articles").readOne(id, {
    fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
  });

  const formattedArticle = {
    ...article,
    publish_date: formatRelativeTime(new Date(article.publish_date)),
  };

  const moreArticlesResponse = await directus.items("articles").readByQuery({
    fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
    filter: {
      _and: [{ id: { _neq: article.id } }, { status: { _eq: "published" } }],
    },
    limit: 2,
  });
  const formattedMoreArticles = moreArticlesResponse.data.map((moreArticle) => {
    return {
      ...moreArticle,
      publish_date: formatRelativeTime(new Date(moreArticle.publish_date)),
    };
  });

  return {
    props: { article: formattedArticle, moreArticles: formattedMoreArticles },
  };
}

// qwik/src/routes/articles/[id]/index.tsx
import { component$, useSignal, useTask$, useVisibleTask$ } from '@builder.io/qwik';
import { Link, useNavigate, useLocation, routeLoader$ } from '@builder.io/qwik-city';

import MoreArticles from "../../../components/MoreArticles";
import IconBack from "../../../components/icons/Back";
import IconLink from "../../../components/icons/Link";
import IconGithub from "../../../components/icons/Github";
import IconYoutube from "../../../components/icons/Youtube";
import IconLinkedin from "../../../components/icons/Linkedin";
import IconTwitter from "../../../components/icons/Twitter";

import { directus } from "../../../services/directus";
import { formatRelativeTime } from "../../../utils/format-relative-time";
import { getAssetURL } from "../../../utils/get-asset-url";

 
export const useArticleLoader = routeLoader$(async ({ params, status }) => {
  try {
    const articleResponse = await directus.items("articles").readOne(params.id, {
      fields: [
        "*",
        "author.avatar",
        "author.first_name",
        "author.last_name",
      ],
    });

    const formattedArticle = {
      ...articleResponse,
      publish_date: formatRelativeTime(
        new Date(articleResponse.publish_date)
      ),
    };

    return formattedArticle;
  } catch (err) {
    return status(404);
  }
});
 
export const useMoreArticlesLoader = routeLoader$(async ({ params, status }) => {
  const moreArticlesResponse = await directus.items("articles").readByQuery({
    fields: [
      "*",
      "author.avatar",
      "author.first_name",
      "author.last_name",
    ],
    filter: {
      _and: [
        { id: { _neq: params.id } },
        { status: { _eq: "published" } },
      ],
    },
    limit: 2,
  });

  const formattedMoreArticles = moreArticlesResponse.data.map(
    (moreArticle) => {
      return {
        ...moreArticle,
        publish_date: formatRelativeTime(
          new Date(moreArticle.publish_date)
        ),
      };
    }
  );

  return formattedMoreArticles;
});


export default component$(() => {
  const article = useArticleLoader();
  const moreArticles = useMoreArticlesLoader();

  const navigate = useNavigate();
  const location = useLocation();
  const { id } = location.params;

  useVisibleTask$(() => {
    document.documentElement.scrollTo(0, 0);
  });

  return (
    <div class="current-article">
      {article.value && (
        <section>
          <div class="container">
            <Link href="/" class="current-article__backlink">
              <IconBack className="icon" />
              <span>Back to Articles</span>
            </Link>
            <h1 class="current-article__title">{article.value.title}</h1>
            <div class="current-article__detail">
              <div class="current-article__wrapperOuter">
                <div class="current-article__wrapperInner">
                  <div class="current-article__authorImage">
                    <img
                      src={getAssetURL(article.value.author.avatar)}
                      alt=""
                      loading="lazy"
                    />
                  </div>
                  <div>
                    <div class="current-article__authorName">
                      {`${article.value.author.first_name} ${article.value.author.last_name}`}
                    </div>
                    <div class="current-article__time">
                      {article.value.publish_date}
                    </div>
                  </div>
                </div>
                <ul class="current-article__socials">
                  <li>
                    <a
                      href={`/articles/${article.value.id}`}
                      target="_blank"
                      rel="noreferrer noopener"
                    >
                      <IconLink />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://www.youtube.com/c/DirectusVideos"
                      target="_blank"
                      rel="noreferrer noopener"
                    >
                      <IconYoutube />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://www.linkedin.com/company/directus-io"
                      target="_blank"
                      rel="noreferrer noopener"
                    >
                      <IconLinkedin />
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://twitter.com/directus"
                      target="_blank"
                      rel="noreferrer noopener"
                    >
                      <IconTwitter />
                    </a>
                  </li>
                </ul>
              </div>
              <div class="current-article_coverImage">
                <img src={getAssetURL(article.value.cover_image)} alt="" />
              </div>
            </div>
            <div class="current-article__body">
              <div
                class="current-article__bodyContent"
                dangerouslySetInnerHTML={article.value.body}
              ></div>
              <ul class="current-article__bodySocials">
                <li>
                  <a
                    href="https://github.com/directus"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconGithub />
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.youtube.com/c/DirectusVideos"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconYoutube />
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.linkedin.com/company/directus-io"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconLinkedin />
                  </a>
                </li>
                <li>
                  <a
                    href="https://twitter.com/directus"
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    <IconTwitter />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </section>
      )}

      {moreArticles.value && <MoreArticles articles={moreArticles} />}
    </div>
  );
});
