// svelte/src/components/MoreArticles.svelte
<script>
  import Article from "./Article.svelte";
  export let articles;
</script>

<section class="more-articles">
  <div class="container">
    <h1 class="more-articles__title">More Articles</h1>
    {#if articles}
      <div class="articles-grid">
        {#each articles as article, index}
          <Article {article} bordered={index !== articles.length - 1} />
        {/each}
      </div>
    {/if}
  </div>
</section>

// gatsby/src/components/moreArticles.jsx
import * as React from "react";
import Article from "./Article";

export default function MoreArticles({ articles }) {
  return (
    <section className="more-articles">
      <div className="container">
        <h1 className="more-articles__title">More Articles</h1>
        {articles?.length !== 0 && (
          <div className="articles-grid">
            {articles.map((article, index) => (
              <Article
                key={index}
                article={article}
                bordered={index !== articles.length - 1}
              />
            ))}
          </div>
        )}
      </div>
    </section>
  );
}
