// nuxtjs/components/MoreArticles.vue
<template>
  <section class="more-articles">
    <div class="container">
      <h1 class="more-articles__title">More Articles</h1>
      <div v-if="articles.length !== 0" class="articles-grid">
        <Article
          v-for="(article, index) in articles"
          :key="index"
          :article="article"
          :bordered="index !== articles.length - 1"
        />
      </div>
    </div>
  </section>
</template>

<script>
import { formatRelativeTime } from "../../shared/utils/format-relative-time";

export default {
  data() {
    return {
      articles: []
    };
  },
  async fetch() {
    const response = await this.$directus.items("articles").readByQuery({
      fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
      limit: 2
    });
    const formattedArticles = response.data.map(article => {
      return {
        ...article,
        publish_date: formatRelativeTime(new Date(article.publish_date))
      };
    });
    this.articles = formattedArticles;
  }
};
</script>

// gatsby/src/components/moreArticles.jsx
import * as React from "react";
import { graphql, useStaticQuery } from "gatsby";
import Article from "./Article";
import { formatRelativeTime } from "../../../shared/utils/format-relative-time";

export default function MoreArticles() {
  const data = useStaticQuery(graphql`
    query {
      directus {
        articles(limit: 2) {
          id
          title
          publish_date
          author {
            first_name
            last_name
            avatar {
              id
            }
          }
          cover_image {
            id
          }
        }
      }
    }
  `);

  const formattedArticles = data.directus.articles.map((article) => {
    return {
      ...article,
      publish_date: formatRelativeTime(new Date(article.publish_date)),
    };
  });
  const articles = formattedArticles;

  return (
    <section className="more-articles">
      <div className="container">
        <h1 className="more-articles__title">More Articles</h1>
        {articles.length !== 0 && (
          <div className="articles-grid">
            {articles.map((article, index) => (
              <Article
                key={index}
                article={article}
                bordered={index !== articles.length - 1}
              />
            ))}
          </div>
        )}
      </div>
    </section>
  );
}
