// svelte/src/App.svelte
<script>
  import { Router, Route } from "svelte-navigator";
  import Notice from "./components/Notice.svelte";
  import Header from "./components/Header.svelte";
  import Info from "./components/Info.svelte";
  import Footer from "./components/Footer.svelte";

  import Home from "./routes/Home.svelte";
  import Article from "./routes/Article.svelte";
  import NotFound from "./routes/NotFound.svelte";
</script>

<div class="layout">
  <Notice />
  <Header />
  <Router>
    <Route path="/">
      <Home />
    </Route>
    <Route path="/articles/:id">
      <Article />
    </Route>
    <Route path="*">
      <NotFound />
    </Route>
  </Router>
  <Info />
  <Footer />
</div>

// vue/src/App.vue
<script setup>
import { RouterView } from "vue-router";
import Notice from "@/components/Notice.vue";
import Header from "@/components/Header.vue";
import Info from "@/components/Info.vue";
import Footer from "@/components/Footer.vue";
</script>

<template>
  <div class="layout">
    <Notice />
    <Header />
    <RouterView :key="$route.fullPath" />
    <Info />
    <Footer />
  </div>
</template>
