// vue/src/App.vue
<script setup>
import { RouterView } from "vue-router";
import Notice from "@/components/Notice.vue";
import Header from "@/components/Header.vue";
import Info from "@/components/Info.vue";
import Footer from "@/components/Footer.vue";
</script>

<template>
  <div class="layout">
    <Notice />
    <Header />
    <RouterView :key="$route.fullPath" />
    <Info />
    <Footer />
  </div>
</template>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: []
})
export class AppComponent {
  title = 'directus-angular-example';
}

<div class="layout">
  <app-notice></app-notice>
  <app-header></app-header>
  <router-outlet></router-outlet>
  <app-info></app-info>
  <app-footer></app-footer>
</div>
