// angular/src/app/pages/not-found/not-found.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'page-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.css']
})
export class NotFoundPage implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<main class="error">
  <section>
    <div class="container">
      <h1>Uh-oh, we can't seem to find the page you're looking for.</h1>
      <p>
        <a href="/">Click here</a> to head back to the safety of the
        homepage.
      </p>
    </div>
  </section>
</main>

// svelte/src/routes/NotFound.svelte
<script>
  import { Link } from "svelte-navigator";
</script>

<main class="error">
  <section>
    <div class="container">
      <h1>Uh-oh, we can't seem to find the page you're looking for.</h1>
      <p>
        <Link to="/">Click here</Link> to head back to the safety of the homepage.
      </p>
    </div>
  </section>
</main>
