// sveltekit/src/lib/components/Info.svelte
<section class="info">
	<div class="info__background">
		<div class="info__backgroundLeft" />
		<div class="info__backgroundRight" />
	</div>
	<div class="container">
		<div class="info__wrapperOuter left">
			<div class="info_wrapperInner">
				<span class="info__subtitle">Documentation</span>
				<a href="#" class="info__title"> Read the Tutorial </a>
			</div>
		</div>
		<div class="info__wrapperOuter right">
			<div class="info_wrapperInner">
				<span class="info__subtitle">Codebase</span>
				<a href="#" class="info__title"> View on GitHub </a>
			</div>
		</div>
	</div>
</section>

// blitz/app/components/Info.jsx
export default function Info() {
  return (
    <section className="info">
      <div className="info__background">
        <div className="info__backgroundLeft"></div>
        <div className="info__backgroundRight"></div>
      </div>
      <div className="container">
        <div className="info__wrapperOuter left">
          <div className="info_wrapperInner">
            <span className="info__subtitle">Documentation</span>
            <a href="#" className="info__title">
              Read the Tutorial
            </a>
          </div>
        </div>
        <div className="info__wrapperOuter right">
          <div className="info_wrapperInner">
            <span className="info__subtitle">Codebase</span>
            <a href="#" className="info__title">
              View on GitHub
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}
