// qwik/src/components/Notice.tsx
import { component$ } from '@builder.io/qwik';

export default component$(() => {
  return (
    <div class="notice">
      <div class="container">
        <span>
          The source code for this blog is{" "}
          <a
            href="https://github.com/directus/examples"
            target="_blank"
            rel="noreferrer"
          >
            available on GitHub.
          </a>
        </span>
        <i class="material-icons-outlined">close</i>
      </div>
    </div>
  );
});

// blitz/app/components/Notice.jsx
export default function Notice() {
  return (
    <div className="notice">
      <div className="container">
        <span>
          The source code for this blog is{" "}
          <a href="https://github.com/directus/examples" target="_blank" rel="noreferrer">
            available on GitHub.
          </a>
        </span>
        <i className="material-icons-outlined">close</i>
      </div>
    </div>
  )
}
