// blitz/app/components/Notice.jsx
export default function Notice() {
  return (
    <div className="notice">
      <div className="container">
        <span>
          The source code for this blog is{" "}
          <a href="https://github.com/directus/examples" target="_blank" rel="noreferrer">
            available on GitHub.
          </a>
        </span>
        <i className="material-icons-outlined">close</i>
      </div>
    </div>
  )
}

// angular/src/app/components/notice/notice.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-notice',
  templateUrl: './notice.component.html',
  styleUrls: ['./notice.component.css']
})
export class NoticeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="notice">
  <div class="container">
    <span>
      The source code for this blog is
      <a
        href="https://github.com/directus/examples"
        target="_blank"
        rel="noreferrer"
      >
        available on GitHub.
      </a>
    </span>
    <i class="material-icons-outlined">close</i>
  </div>
</div>
