// svelte/src/components/Header.svelte
<script>
  import MonospaceIcon from "./icons/Monospace.svelte";
</script>

<header>
  <nav class="container">
    <a href="/"><MonospaceIcon /></a>
    <span class="header__description">
      An example site powered by <span class="accent">Svelte</span> and
      <span class="accent">Directus</span>.
    </span>
  </nav>
</header>

// react/src/components/Header.jsx
import IconMonospace from "./icons/Monospace";

export default function Header() {
  return (
    <header>
      <nav className="container">
        <a href="/">
          <IconMonospace />
        </a>
        <span className="header__description">
          An example site powered by <span className="accent">React</span> and{" "}
          <span className="accent">Directus</span>.
        </span>
      </nav>
    </header>
  );
}
