// gatsby/src/pages/index.jsx
import React from "react";
import DefaultLayout from "../layouts/default";
import Hero from "../components/hero";
import Article from "../components/article";
import { formatRelativeTime } from "../utils/format-relative-time";
import { graphql } from "gatsby";

const IndexPage = ({ data }) => {
  const formattedArticles = data.directus.articles.map((article) => {
    return {
      ...article,
      date_created: formatRelativeTime(new Date(article.date_created)),
    };
  });
  const [hero, ...articles] = formattedArticles;

  return (
    <DefaultLayout>
      <main>
        <section className="main-content">
          <div className="container">
            <Hero article={hero} />
            <div className="articles-grid">
              {articles.map((article, index) => (
                <Article
                  key={index}
                  article={article}
                  bordered={index !== articles.length - 1}
                />
              ))}
            </div>
          </div>
        </section>
      </main>
    </DefaultLayout>
  );
};

export const query = graphql`
  query {
    directus {
      articles(sort: "date_created") {
        id
        title
        excerpt
        date_created
        author {
          first_name
          last_name
          avatar {
            id
          }
        }
        cover_image {
          id
        }
      }
    }
  }
`;

export default IndexPage;

// nuxtjs/pages/index.vue
<template>
  <main>
    <section class="main-content">
      <div class="container">
        <Hero :article="hero" />
        <div class="articles-grid">
          <Article
            v-for="(article, index) in articles"
            :key="index"
            :article="article"
            :bordered="index !== articles.length - 1"
          />
        </div>
      </div>
    </section>
  </main>
</template>

<script>
import { formatRelativeTime } from "@/utils/format-relative-time";

export default {
  async asyncData({ $directus }) {
    const response = await $directus.items("articles").readMany({
      fields: ["*", "author.avatar", "author.first_name", "author.last_name"],
      sort: "publish_date"
    });
    const formattedArticles = response.data.map(article => {
      return {
        ...article,
        publish_date: formatRelativeTime(new Date(article.publish_date))
      };
    });
    const [hero, ...articles] = formattedArticles;
    return { hero, articles };
  }
};
</script>
