// website-next13/app/blog/page.tsx
import directus from "lib/directus"

async function getPosts() {
  const posts = await directus.items('posts').readByQuery({
    fields: ['slug', 'title', 'publish_date', 'author.name'],
    sort: ['-publish_date']
  })
  return posts.data
}

export default async function DynamicPage() {
  const posts = await getPosts()
  return (
    <div>
      <h1>Blog</h1>
      <ul>
        {posts.map(post => {
          return (
            <li key={post.slug}>
              <a href={`/blog/${post.slug}`}>
                <h2>{post.title}</h2>
              </a>
              <span>{post.publish_date} &bull; {post.author.name}</span>
            </li>
          )
        })}
      </ul>
    </div>
  )
}

// website-nuxt3/pages/blog/index.vue
<template>
  <h1>Blog</h1>
  <ul>
    <li v-for="post in posts.data">
      <NuxtLink :href="`/blog/${post.slug}`">
        <h2>{{post.title}}</h2>
      </NuxtLink>
      <span>{{post.publish_date}} &bull; {{post.author.name}}</span>
    </li>
  </ul>
</template>


<script setup>
  const { $directus } = useNuxtApp()
  const { data: posts } = await useAsyncData('posts', () => {
    return $directus.items('posts').readByQuery({
      fields: ['slug', 'title', 'publish_date', 'author.name'],
      sort: ['-publish_date']
    })
  })
</script>
